### ISSUE TITLE
I forked the assignment but I cannot find my copy of the fork to submit a link for

### ISSUE THREAD

**Issue by BenMurphyFlatiron** [learn-co-curriculum/phase-0-pac-3-intro-to-functions#5]
I am unsure of how to submit the assignment considering that I cannot find the repository.

**Comment by graciemcguire** [comment]
Hello @BenMurphyFlatiron ! Thanks for raising this issue.  The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

If you go to the GitHub repository for this lab (https://github.com/learn-co-curriculum/phase-0-pac-3-intro-to-functions), and click `fork`, it should link you to your already-created fork. 

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!

Thanks! 💙
