### ISSUE TITLE
Not Working on my Terminal

### ISSUE THREAD

**Issue by Jeremy-Tpk-the-software-engineer** [learn-co-curriculum/phase-0-pac-3-intro-to-functions#7]
### Canvas Link

https://learning.flatironschool.com/courses/5631/pages/introduction-to-functions-in-javascript?module_item_id=385629

### Concern

Im using Visual Studio (MacOs). Everything I was doing on the previous lessons were working until this lesson.
Everything I am doing not working and this is what I am getting when im trying to run on my terminal 

jeremy@Jeremys-MacBook-Pro phase-1 % node index.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/jeremy/Development/code/phase-1/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
jeremy@Jeremys-MacBook-Pro phase-1 % 

### Additional Context

So, for now I can't continue with other lessons until I complete this one and understand it. 

thank you !

**Comment by lizbur10** [comment]
Hi there! Thanks for raising this issue. Based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
